# Site
name: Raju Talukder
description: Raju Talukder's blog
meta_description: Raju Talukder's blog
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'rajutalukder70@gmail.com'
google_analytics: UA-103662447-9
disqus:
sharethis:

# Authors
authors:
  raju:
    name: Raju
    display_name: r@ju
    image: /assets/images/raju.jpeg
    email: rajutalukder70@gmail.com
    web: https://raju-talukder.github.io/
    twitter:
    description: Hi, I am Raju Talukder.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: raju
  card: summary

facebook:
  app_id:
  publisher: https://raju-talukder.github.io/
  admins:

social:
name: Raju Talukder
links:
    - https://www.facebook.com/rajutalukder70/
    - https://www.linkedin.com/in/rajutalukder
    - https://github.com/Raju-Talukder
