title: "Your Portfolio Title"
name: "Your Name"
email: "your-email@example.com"
description: >- 
  Cybersecurity engineer, researcher, and blog writer.
url: "https://your-github-username.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: your-github-username/your-repo-name
logo: "/assets/images/profile.png"
masthead_title: "Your Portfolio"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives

# Comments configuration
comments:
  provider: "giscus"
  giscus:
    repo_id: "YOUR_REPO_ID"
    category_name: "General"
    category_id: "YOUR_CATEGORY_ID"
    discussion_term: "pathname"
    reactions_enabled: '1'
    theme: "dark"
    input_position: "bottom"
    emit_metadata: '0'
    lang: "en"
    lazy: true

# Author information
author:
  name: "Your Name"
  avatar: "/assets/images/profile.png"
  bio: "Cybersecurity Engineer | Threat Hunter | CVE Researcher"
  location: "Your Location"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your-email@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/your-github-username"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/your-linkedin-profile"
    - label: "Blog"
      icon: "fas fa-book"
      url: "/blog/"

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

# SEO
seo:
  type: "Person"
  name: "Your Name"
  description: "Cybersecurity researcher and engineer portfolio"
  url: "https://your-github-username.github.io"
  image: "/assets/images/profile.png"
  twitter: your-twitter-handle

# Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Social Sharing
twitter:
  username: your-twitter-handle

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
