name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 👈 needed to allow pushing to main

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main  # 👈 deploy to `main` not `gh-pages`
          force_orphan: false   # 👈 don't force overwrite main
